const DB_NAME='dbPlumbingLedgerDB', DB_VERSION=1;
let db, installPrompt=null, currentEntryFilter='all';
const $=id=>document.getElementById(id);
const money=n=>new Intl.NumberFormat('en-MT',{style:'currency',currency:'EUR'}).format(Number(n||0));
const today=()=>new Date().toISOString().slice(0,10);
const uid=()=>crypto.randomUUID ? crypto.randomUUID() : `${Date.now()}-${Math.random()}`;

function openDB(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB_NAME,DB_VERSION);r.onupgradeneeded=e=>{const d=e.target.result;if(!d.objectStoreNames.contains('entries')) d.createObjectStore('entries',{keyPath:'id'});if(!d.objectStoreNames.contains('clients')) d.createObjectStore('clients',{keyPath:'id'});if(!d.objectStoreNames.contains('settings')) d.createObjectStore('settings',{keyPath:'key'});if(!d.objectStoreNames.contains('files')) d.createObjectStore('files',{keyPath:'id'});};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
function tx(store,mode='readonly'){return db.transaction(store,mode).objectStore(store)}
function getAll(store){return new Promise((res,rej)=>{const r=tx(store).getAll();r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
function getOne(store,key){return new Promise((res,rej)=>{const r=tx(store).get(key);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
function put(store,val){return new Promise((res,rej)=>{const r=tx(store,'readwrite').put(val);r.onsuccess=()=>res(val);r.onerror=()=>rej(r.error)})}
function del(store,key){return new Promise((res,rej)=>{const r=tx(store,'readwrite').delete(key);r.onsuccess=()=>res();r.onerror=()=>rej(r.error)})}
function clearStore(store){return new Promise((res,rej)=>{const r=tx(store,'readwrite').clear();r.onsuccess=()=>res();r.onerror=()=>rej(r.error)})}
async function setting(key,def=''){const r=await getOne('settings',key);return r? r.value:def}
async function setSetting(key,value){return put('settings',{key,value})}

async function init(){db=await openDB();await ensureDefaults();bind();await refreshAll();if('serviceWorker'in navigator) navigator.serviceWorker.register('service-worker.js').catch(()=>{});}
async function ensureDefaults(){const defaults={legalName:'Dennis Bendinelli',tradeName:'DB Plumbing Services',vatStatus:'article11',article10Date:'',vatRate:'18'};for(const[k,v]of Object.entries(defaults))if((await getOne('settings',k))==null)await setSetting(k,v)}

function bind(){
 document.querySelectorAll('.nav[data-view]').forEach(b=>b.onclick=()=>showView(b.dataset.view));
 $('quickAdd').onclick=()=>openEntry(); $('addEntryTop').onclick=()=>openEntry(); $('addClientTop').onclick=()=>openClient(); $('openAllBtn').onclick=()=>showView('entries');
 document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$(b.dataset.close).close());
 document.querySelectorAll('.type-choice [data-type]').forEach(b=>b.onclick=()=>setEntryType(b.dataset.type));
 document.querySelectorAll('.segmented:not(.type-choice) [data-filter]').forEach(b=>b.onclick=()=>{currentEntryFilter=b.dataset.filter;b.parentElement.querySelectorAll('.seg').forEach(x=>x.classList.toggle('active',x===b));renderEntries();});
 $('entryForm').addEventListener('submit',saveEntry); $('clientForm').addEventListener('submit',saveClient);
 $('deleteEntry').onclick=deleteCurrentEntry; $('deleteClient').onclick=deleteCurrentClient;
 $('yearFilter').onchange=renderDashboard; $('saveSettings').onclick=saveSettings;
 $('exportCsv').onclick=exportEntriesCSV; $('exportClientsCsv').onclick=exportClientsCSV; $('exportBackup').onclick=exportBackup; $('importBackup').onchange=importBackup; $('clearData').onclick=clearAll;
 window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;$('installBtn').classList.remove('hidden')}); $('installBtn').onclick=async()=>{if(installPrompt){installPrompt.prompt();await installPrompt.userChoice;installPrompt=null;$('installBtn').classList.add('hidden')}};
}
function showView(v){document.querySelectorAll('.view').forEach(x=>x.classList.toggle('active',x.id===v));document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.view===v));if(v==='entries')renderEntries();if(v==='clients')renderClients();if(v==='reports'){}if(v==='settings')loadSettings();window.scrollTo({top:0,behavior:'smooth'})}
async function refreshAll(){await fillYears();await fillClientsSelect();await renderDashboard();await renderEntries();await renderClients();await loadSettings()}
async function fillYears(){const entries=await getAll('entries');const years=new Set(entries.map(e=>e.date?.slice(0,4)).filter(Boolean));years.add(String(new Date().getFullYear()));const cur=$('yearFilter').value||String(new Date().getFullYear());$('yearFilter').innerHTML=[...years].sort().reverse().map(y=>`<option ${y===cur?'selected':''}>${y}</option>`).join('')}
async function renderDashboard(){const entries=await getAll('entries'), y=$('yearFilter').value;const arr=entries.filter(e=>e.date?.startsWith(y));const inc=arr.filter(e=>e.type==='income').reduce((s,e)=>s+Number(e.amount||0),0);const exp=arr.filter(e=>e.type==='expense').reduce((s,e)=>s+Number(e.amount||0),0);const unpaid=arr.filter(e=>e.type==='income'&&e.paid==='unpaid').reduce((s,e)=>s+Number(e.amount||0),0);$('incomeTotal').textContent=money(inc);$('expenseTotal').textContent=money(exp);$('profitTotal').textContent=money(inc-exp);$('unpaidTotal').textContent=money(unpaid);
 const status=await setting('vatStatus','article11');$('vatBadge').textContent=status==='article10'?'Article 10':'Article 11';$('vatCard').classList.toggle('hidden',status!=='article10');if(status==='article10'){const vS=arr.filter(e=>e.type==='income').reduce((s,e)=>s+Number(e.vat||0),0),vP=arr.filter(e=>e.type==='expense').reduce((s,e)=>s+Number(e.vat||0),0);$('vatSales').textContent=money(vS);$('vatPurchases').textContent=money(vP);$('vatBalance').textContent=money(vS-vP)}
 renderList($('recentList'),arr.sort((a,b)=>b.date.localeCompare(a.date)).slice(0,8));}
async function renderEntries(){let arr=await getAll('entries');arr.sort((a,b)=>b.date.localeCompare(a.date));if(currentEntryFilter==='income')arr=arr.filter(e=>e.type==='income');if(currentEntryFilter==='expense')arr=arr.filter(e=>e.type==='expense');if(currentEntryFilter==='unpaid')arr=arr.filter(e=>e.type==='income'&&e.paid==='unpaid');renderList($('entryList'),arr)}
function renderList(el,arr){if(!arr.length){el.innerHTML='<div class="empty">Nessun movimento.</div>';return}el.innerHTML=arr.map(e=>`<button class="row ${e.type}" data-entry="${e.id}"><div><div class="row-title">${esc(e.description)}</div><div class="row-sub">${esc(e.date)}${e.location?' · '+esc(e.location):''}${e.document?' · '+esc(e.document):''}</div>${e.type==='income'&&e.paid==='unpaid'?'<span class="unpaid-pill">Da incassare</span>':''}</div><div class="amount">${e.type==='expense'?'-':'+'}${money(e.amount)}</div></button>`).join('');el.querySelectorAll('[data-entry]').forEach(b=>b.onclick=()=>openEntry(b.dataset.entry))}
function setEntryType(type){$('entryType').value=type;document.querySelectorAll('.type-choice .seg').forEach(b=>b.classList.toggle('active',b.dataset.type===type));$('clientField').classList.toggle('hidden',type==='expense');$('paymentStatusField').classList.toggle('hidden',type==='expense')}
async function openEntry(id=''){const form=$('entryForm');form.reset();$('entryId').value='';$('entryDate').value=today();$('entryVat').value='0';$('deleteEntry').classList.add('hidden');$('receiptCurrent').textContent='';setEntryType('income');await fillClientsSelect();if(id){const e=await getOne('entries',id);if(!e)return;$('entryDialogTitle').textContent='Modifica movimento';$('entryId').value=e.id;setEntryType(e.type);$('entryDate').value=e.date;$('entryClient').value=e.clientId||'';$('entryDescription').value=e.description||'';$('entryLocation').value=e.location||'';$('entryAmount').value=e.amount||'';$('entryVat').value=e.vat||0;$('entryPaid').value=e.paid||'paid';$('entryMethod').value=e.method||'Cash';$('entryDocument').value=e.document||'';$('entryNotes').value=e.notes||'';$('receiptCurrent').textContent=e.fileId?'Documento allegato presente':'';$('deleteEntry').classList.remove('hidden')}else $('entryDialogTitle').textContent='Nuovo movimento';$('entryDialog').showModal()}
async function saveEntry(ev){ev.preventDefault();const id=$('entryId').value||uid();let existing=$('entryId').value?await getOne('entries',id):null;let fileId=existing?.fileId||'';const file=$('entryReceipt').files[0];if(file){if(fileId)await del('files',fileId);fileId=uid();await put('files',{id:fileId,name:file.name,type:file.type,blob:file})}const e={id,type:$('entryType').value,date:$('entryDate').value,clientId:$('entryClient').value,description:$('entryDescription').value.trim(),location:$('entryLocation').value.trim(),amount:Number($('entryAmount').value||0),vat:Number($('entryVat').value||0),paid:$('entryType').value==='income'?$('entryPaid').value:'paid',method:$('entryMethod').value,document:$('entryDocument').value.trim(),notes:$('entryNotes').value.trim(),fileId};await put('entries',e);$('entryDialog').close();await refreshAll()}
async function deleteCurrentEntry(){const id=$('entryId').value;if(!id)return;if(!confirm('Eliminare questo movimento?'))return;const e=await getOne('entries',id);if(e?.fileId)await del('files',e.fileId);await del('entries',id);$('entryDialog').close();await refreshAll()}

async function fillClientsSelect(){const arr=(await getAll('clients')).sort((a,b)=>a.name.localeCompare(b.name));$('entryClient').innerHTML='<option value="">— Nessun cliente —</option>'+arr.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('')}
async function renderClients(){const arr=(await getAll('clients')).sort((a,b)=>a.name.localeCompare(b.name));const el=$('clientList');if(!arr.length){el.innerHTML='<div class="empty">Nessun cliente.</div>';return}el.innerHTML=arr.map(c=>`<button class="row" data-client="${c.id}"><div><div class="row-title">${esc(c.name)}</div><div class="row-sub">${esc(c.phone||'')}${c.location?' · '+esc(c.location):''}</div></div><div>›</div></button>`).join('');el.querySelectorAll('[data-client]').forEach(b=>b.onclick=()=>openClient(b.dataset.client))}
async function openClient(id=''){const f=$('clientForm');f.reset();$('clientId').value='';$('deleteClient').classList.add('hidden');if(id){const c=await getOne('clients',id);if(!c)return;$('clientId').value=c.id;$('clientName').value=c.name;$('clientPhone').value=c.phone||'';$('clientEmail').value=c.email||'';$('clientLocation').value=c.location||'';$('clientNotes').value=c.notes||'';$('deleteClient').classList.remove('hidden')}$('clientDialog').showModal()}
async function saveClient(ev){ev.preventDefault();const c={id:$('clientId').value||uid(),name:$('clientName').value.trim(),phone:$('clientPhone').value.trim(),email:$('clientEmail').value.trim(),location:$('clientLocation').value.trim(),notes:$('clientNotes').value.trim()};await put('clients',c);$('clientDialog').close();await refreshAll()}
async function deleteCurrentClient(){const id=$('clientId').value;if(!id)return;if(!confirm('Eliminare questo cliente? I movimenti resteranno registrati.'))return;await del('clients',id);$('clientDialog').close();await refreshAll()}

async function loadSettings(){$('legalName').value=await setting('legalName','Dennis Bendinelli');$('tradeName').value=await setting('tradeName','DB Plumbing Services');$('vatStatus').value=await setting('vatStatus','article11');$('article10Date').value=await setting('article10Date','');$('vatRate').value=await setting('vatRate','18')}
async function saveSettings(){await setSetting('legalName',$('legalName').value.trim());await setSetting('tradeName',$('tradeName').value.trim());await setSetting('vatStatus',$('vatStatus').value);await setSetting('article10Date',$('article10Date').value);await setSetting('vatRate',$('vatRate').value);await renderDashboard();alert('Impostazioni salvate')}

function csvEscape(v){v=String(v??'');return /[",\n]/.test(v)?`"${v.replace(/"/g,'""')}"`:v}
function downloadBlob(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},500)}
async function exportEntriesCSV(){const clients=Object.fromEntries((await getAll('clients')).map(c=>[c.id,c.name]));const arr=await getAll('entries');const rows=[['Date','Type','Client','Description','Location','Amount EUR','VAT EUR','Payment status','Method','Document','Notes']];arr.sort((a,b)=>a.date.localeCompare(b.date)).forEach(e=>rows.push([e.date,e.type,clients[e.clientId]||'',e.description,e.location,e.amount,e.vat,e.paid,e.method,e.document,e.notes]));downloadBlob(new Blob([rows.map(r=>r.map(csvEscape).join(',')).join('\n')],{type:'text/csv'}),`DB_Plumbing_movimenti_${today()}.csv`)}
async function exportClientsCSV(){const arr=await getAll('clients');const rows=[['Name','Phone','Email','Location','Notes'],...arr.map(c=>[c.name,c.phone,c.email,c.location,c.notes])];downloadBlob(new Blob([rows.map(r=>r.map(csvEscape).join(',')).join('\n')],{type:'text/csv'}),`DB_Plumbing_clienti_${today()}.csv`)}
async function exportBackup(){const data={version:1,exportedAt:new Date().toISOString(),entries:await getAll('entries'),clients:await getAll('clients'),settings:await getAll('settings'),files:[]};for(const f of await getAll('files')){const buf=await f.blob.arrayBuffer();data.files.push({id:f.id,name:f.name,type:f.type,data:arrayBufferToBase64(buf)})}downloadBlob(new Blob([JSON.stringify(data)],{type:'application/json'}),`DB_Plumbing_backup_${today()}.json`)}
function arrayBufferToBase64(buffer){let binary='';const bytes=new Uint8Array(buffer);for(let i=0;i<bytes.byteLength;i++)binary+=String.fromCharCode(bytes[i]);return btoa(binary)}
function base64ToBlob(base64,type){const bin=atob(base64),bytes=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)bytes[i]=bin.charCodeAt(i);return new Blob([bytes],{type})}
async function importBackup(ev){const f=ev.target.files[0];if(!f)return;if(!confirm('Ripristinare questo backup? I dati attuali verranno sostituiti.')){ev.target.value='';return}try{const d=JSON.parse(await f.text());for(const s of ['entries','clients','settings','files'])await clearStore(s);for(const x of d.entries||[])await put('entries',x);for(const x of d.clients||[])await put('clients',x);for(const x of d.settings||[])await put('settings',x);for(const x of d.files||[])await put('files',{id:x.id,name:x.name,type:x.type,blob:base64ToBlob(x.data,x.type)});await ensureDefaults();await refreshAll();alert('Backup ripristinato')}catch(e){alert('Backup non valido')}ev.target.value=''}
async function clearAll(){if(!confirm('Cancellare TUTTI i dati dell’app?'))return;if(!confirm('Confermi definitivamente?'))return;for(const s of ['entries','clients','settings','files'])await clearStore(s);await ensureDefaults();await refreshAll()}
function esc(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}

init();
