(()=>{
'use strict';
const KEY='propertyAssetsV1',MAINT_KEY='maintenancePlansV1';
let M,assets=[],currentPropertyId='',currentAssetId='',jobSaveMetaPromise=null;
const wait=()=>{M=window.DBM;if(!M?.setting||!M?.lPut||!M?.mAll||!M?.mOne||!M?.mPut||!M?.propertiesForClient||!M?.openJob||!document.getElementById('dbmPropertyDialog')||!document.getElementById('dbmJobForm'))return setTimeout(wait,100);init()};
const esc=s=>M.esc?M.esc(s):String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const fmt=s=>{if(!s)return'—';const p=String(s).split('-');return p.length===3?`${p[2]}/${p[1]}/${p[0]}`:s};
const norm=s=>String(s||'').toLowerCase().replace(/\s+/g,' ').trim();
async function loadAssets(){const raw=await M.setting(KEY,'');try{const x=raw?JSON.parse(raw):[];assets=Array.isArray(x)?x:[]}catch{assets=[]}}
const saveAssets=()=>M.lPut('settings',{key:KEY,value:JSON.stringify(assets)});
async function loadMaint(){const raw=await M.setting(MAINT_KEY,'');try{const x=raw?JSON.parse(raw):[];return Array.isArray(x)?x:[]}catch{return[]}}
const saveMaint=a=>M.lPut('settings',{key:MAINT_KEY,value:JSON.stringify(a)});
const planId=id=>`asset-maint-${id}`;
function init(){if(M.__propertyAssetsReady)return;M.__propertyAssetsReady=true;styles();injectPropertyPanel();injectAssetDialog();injectJobFields();hookPropertyDialog();hookJobs();M.assetsForProperty=async id=>{await loadAssets();return assets.filter(a=>a.propertyId===id).sort((x,y)=>(x.name||'').localeCompare(y.name||''))};M.assetById=async id=>{await loadAssets();return assets.find(a=>a.id===id)||null};loadAssets().then(renderPropertyAssets)}
function styles(){if(document.getElementById('dbmAssetStyles'))return;const s=document.createElement('style');s.id='dbmAssetStyles';s.textContent=`
.dbm-assets{margin-top:14px;padding-top:12px;border-top:1px solid #e3ebf1}.dbm-assets-head{display:flex;justify-content:space-between;align-items:center;gap:8px}.dbm-assets-head h3{margin:0}.dbm-assets-list{display:grid;gap:8px;margin-top:8px}.dbm-asset-card{display:grid;grid-template-columns:54px minmax(0,1fr);gap:10px;align-items:center;width:100%;border:1px solid #dce6ee;background:#f8fbfd;border-radius:13px;padding:9px;text-align:left;color:#0b1f35}.dbm-asset-card.no-photo{grid-template-columns:1fr}.dbm-asset-thumb{width:54px;height:54px;object-fit:cover;border-radius:10px;border:1px solid #dce6ee;background:#fff}.dbm-asset-card b{display:block;font-size:12px}.dbm-asset-card span{display:block;font-size:9.5px;color:#64748b;margin-top:2px;line-height:1.35}.dbm-asset-dialog{width:min(calc(100vw - 18px),620px);max-width:620px}.dbm-asset-preview{display:none;margin:8px 0 4px}.dbm-asset-preview.show{display:block}.dbm-asset-preview img{width:100%;max-height:230px;object-fit:contain;background:#f8fbfd;border:1px solid #dce6ee;border-radius:12px}.dbm-asset-meta{display:grid;grid-template-columns:1fr 1fr;gap:8px}.dbm-asset-link{margin-top:10px;border:1px solid #dce6ee;border-radius:12px;padding:10px;background:#f8fbfd}.dbm-asset-link b{display:block;font-size:11px}.dbm-asset-link span{display:block;font-size:9.5px;color:#64748b;margin-top:2px}.dbm-job-asset-fields{display:grid;grid-template-columns:1fr 1fr;gap:10px}@media(max-width:600px){.dbm-job-asset-fields,.dbm-asset-meta{grid-template-columns:1fr}.dbm-asset-dialog input,.dbm-asset-dialog select,.dbm-asset-dialog textarea{font-size:17px!important}}
`;document.head.appendChild(s)}
function injectPropertyPanel(){const hist=document.getElementById('dbmPropertyHistory');if(!hist||document.getElementById('dbmAssetsPanel'))return;hist.insertAdjacentHTML('afterend',`<section id="dbmAssetsPanel" class="dbm-assets"><div class="dbm-assets-head"><div><h3>Impianti / apparecchiature</h3><div class="hint">Scheda tecnica della proprietà: A/C, geyser, pompe, boiler e altri impianti.</div></div><button type="button" id="dbmAddAsset" class="secondary small">+ Impianto</button></div><div id="dbmAssetsList" class="dbm-assets-list"></div></section>`);document.getElementById('dbmAddAsset').onclick=()=>openAsset()}
function injectAssetDialog(){if(document.getElementById('dbmAssetDialog'))return;document.body.insertAdjacentHTML('beforeend',`<dialog id="dbmAssetDialog" class="dbm-asset-dialog"><form id="dbmAssetForm" method="dialog"><div class="dialog-head"><h2 id="dbmAssetTitle">Impianto</h2><button type="button" class="icon" data-close-asset>×</button></div><input id="dbmAssetId" type="hidden"><label>Tipo<select id="dbmAssetType"><option>A/C</option><option>Water heater / geyser</option><option>Pompa</option><option>Boiler / riscaldamento</option><option>WC / sanitario</option><option>MVHR / ventilazione</option><option>Altro</option></select></label><label>Nome / posizione<input id="dbmAssetName" required placeholder="Es. A/C soggiorno"></label><div class="dbm-asset-meta"><label>Marca<input id="dbmAssetBrand" placeholder="Es. Hisense"></label><label>Modello<input id="dbmAssetModel"></label></div><label>Numero seriale<input id="dbmAssetSerial"></label><div class="dbm-asset-meta"><label>Data installazione<input id="dbmAssetInstalled" type="date"></label><label>Garanzia fino al<input id="dbmAssetWarranty" type="date"></label></div><label>Foto impianto<input id="dbmAssetPhoto" type="file" accept="image/*" capture="environment"></label><div id="dbmAssetPreview" class="dbm-asset-preview"><img id="dbmAssetPreviewImg" alt="Foto impianto"></div><label>Note tecniche<textarea id="dbmAssetNotes" rows="3" placeholder="Posizione, accesso, particolarità, ricambi..."></textarea></label><div class="dbm-asset-link"><b>Manutenzione ricorrente</b><span>Se attiva, usa la stessa agenda manutenzioni già presente nell'app.</span><label style="margin-top:7px">Frequenza<select id="dbmAssetMaintMonths"><option value="0">Nessuna</option><option value="3">Ogni 3 mesi</option><option value="6">Ogni 6 mesi</option><option value="12">Ogni 12 mesi</option><option value="24">Ogni 24 mesi</option></select></label><label>Prossima scadenza<input id="dbmAssetMaintNext" type="date"></label></div><div id="dbmAssetLastWork" class="dbm-asset-link"></div><button class="primary full" value="save">Salva impianto</button><button id="dbmDeleteAsset" type="button" class="danger full hidden">Elimina impianto</button></form></dialog>`);document.querySelector('[data-close-asset]').onclick=()=>document.getElementById('dbmAssetDialog').close();document.getElementById('dbmAssetForm').addEventListener('submit',saveAsset);document.getElementById('dbmDeleteAsset').onclick=deleteAsset;document.getElementById('dbmAssetPhoto').addEventListener('change',previewPhoto)}
function injectJobFields(){const client=document.getElementById('dbmJobClient');if(!client||document.getElementById('dbmJobAssetFields'))return;const label=client.closest('label');label.insertAdjacentHTML('afterend',`<div id="dbmJobAssetFields" class="dbm-job-asset-fields"><label>Proprietà<select id="dbmJobProperty"><option value="">— Nessuna proprietà —</option></select></label><label>Impianto / apparecchiatura<select id="dbmJobAsset"><option value="">— Nessun impianto —</option></select></label></div>`);document.getElementById('dbmJobClient').addEventListener('change',async()=>{await fillJobProperties('');await fillJobAssets('')});document.getElementById('dbmJobProperty').addEventListener('change',async()=>{await fillJobAssets('');const p=await M.propertyById?.(document.getElementById('dbmJobProperty').value);if(p?.address&&!document.getElementById('dbmJobLocation').value.trim())document.getElementById('dbmJobLocation').value=p.address})}
function hookPropertyDialog(){const d=document.getElementById('dbmPropertyDialog');const sync=()=>{currentPropertyId=document.getElementById('dbmPropertyId')?.value||'';const add=document.getElementById('dbmAddAsset');if(add)add.disabled=!currentPropertyId;renderPropertyAssets()};d.addEventListener('toggle',sync);d.addEventListener('close',()=>{currentPropertyId=''});const originalShow=d.showModal.bind(d);d.showModal=()=>{const r=originalShow();setTimeout(sync,0);return r}}
async function renderPropertyAssets(){const list=document.getElementById('dbmAssetsList');if(!list)return;await loadAssets();currentPropertyId=document.getElementById('dbmPropertyId')?.value||currentPropertyId;if(!currentPropertyId){list.innerHTML='<div class="dbm-prop-empty">Salva prima la proprietà, poi potrai aggiungere gli impianti.</div>';return}const a=assets.filter(x=>x.propertyId===currentPropertyId).sort((x,y)=>(x.name||'').localeCompare(y.name||''));if(!a.length){list.innerHTML='<div class="dbm-prop-empty">Nessun impianto registrato per questa proprietà.</div>';return}const jobs=await M.mAll('jobs'),maint=await loadMaint();list.innerHTML=a.map(x=>{const last=lastWorkFor(x,jobs),plan=maint.find(p=>p.id===planId(x.id));const meta=[x.type,x.brand,x.model].filter(Boolean).join(' · ');const sub=[meta,x.serial?'S/N '+x.serial:'',last?`ultimo ${fmt(last.date)}`:'',plan?.nextDate?`prossima manut. ${fmt(plan.nextDate)}`:''].filter(Boolean).join(' · ');return `<button type="button" class="dbm-asset-card ${x.imageDataUrl?'':'no-photo'}" data-asset="${esc(x.id)}">${x.imageDataUrl?`<img class="dbm-asset-thumb" src="${x.imageDataUrl}" alt="${esc(x.name)}">`:''}<div><b>${esc(x.name)}</b><span>${esc(sub||'Scheda tecnica')}</span></div></button>`}).join('');list.querySelectorAll('[data-asset]').forEach(b=>b.onclick=()=>openAsset(b.dataset.asset))}
function jobsForProperty(propertyId,jobs=[]){const pId=propertyId||'';return jobs.filter(j=>j.propertyId===pId).sort((a,b)=>(b.date||'').localeCompare(a.date||''))}
function lastWorkFor(asset,jobs=[]){const direct=jobs.filter(j=>j.assetId===asset.id).sort((a,b)=>(b.date||'').localeCompare(a.date||''));if(direct.length)return direct[0];return jobsForProperty(asset.propertyId,jobs)[0]||null}
async function openAsset(id=''){currentPropertyId=document.getElementById('dbmPropertyId')?.value||currentPropertyId;if(!currentPropertyId){alert('Salva prima la proprietà.');return}await loadAssets();const a=id?assets.find(x=>x.id===id):null;currentAssetId=a?.id||'';const f=document.getElementById('dbmAssetForm');f.reset();document.getElementById('dbmAssetId').value=currentAssetId;document.getElementById('dbmAssetTitle').textContent=a?'Modifica impianto':'Nuovo impianto';document.getElementById('dbmAssetType').value=a?.type||'A/C';document.getElementById('dbmAssetName').value=a?.name||'';document.getElementById('dbmAssetBrand').value=a?.brand||'';document.getElementById('dbmAssetModel').value=a?.model||'';document.getElementById('dbmAssetSerial').value=a?.serial||'';document.getElementById('dbmAssetInstalled').value=a?.installedDate||'';document.getElementById('dbmAssetWarranty').value=a?.warrantyUntil||'';document.getElementById('dbmAssetNotes').value=a?.notes||'';setPreview(a?.imageDataUrl||'');const maint=await loadMaint(),plan=maint.find(p=>p.id===planId(currentAssetId));document.getElementById('dbmAssetMaintMonths').value=String(plan?.months||0);document.getElementById('dbmAssetMaintNext').value=plan?.nextDate||'';document.getElementById('dbmDeleteAsset').classList.toggle('hidden',!a);await renderAssetLastWork(a);document.getElementById('dbmAssetDialog').showModal()}
async function renderAssetLastWork(a){const el=document.getElementById('dbmAssetLastWork');if(!a){el.innerHTML='<b>Storico impianto</b><span>Gli interventi collegati appariranno qui.</span>';return}const jobs=await M.mAll('jobs'),last=lastWorkFor(a,jobs);el.innerHTML=last?`<b>Ultimo intervento</b><span>${esc(last.title||'Intervento')} · ${fmt(last.date)} · ${esc(statusLabel(last.status))}</span>`:'<b>Ultimo intervento</b><span>Nessun intervento collegato ancora.</span>'}
function statusLabel(s){return({quote:'Bozza',quote_sent:'Inviato',quote_accepted:'Accettato',scheduled:'Da programmare',active:'In corso',waiting:'In attesa',completed:'Completato'}[s]||s||'—')}
function previewPhoto(){const f=document.getElementById('dbmAssetPhoto').files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>setPreview(String(r.result||''));r.readAsDataURL(f)}
function setPreview(src){const box=document.getElementById('dbmAssetPreview'),img=document.getElementById('dbmAssetPreviewImg');img.src=src||'';box.classList.toggle('show',!!src)}
async function compressedPhoto(file,existing=''){if(!file)return existing;const data=await new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=()=>rej(r.error);r.readAsDataURL(file)});const img=await new Promise((res,rej)=>{const i=new Image();i.onload=()=>res(i);i.onerror=rej;i.src=data});const max=1200,scale=Math.min(1,max/Math.max(img.width,img.height)),w=Math.max(1,Math.round(img.width*scale)),h=Math.max(1,Math.round(img.height*scale)),c=document.createElement('canvas');c.width=w;c.height=h;c.getContext('2d').drawImage(img,0,0,w,h);return c.toDataURL('image/jpeg',0.76)}
async function syncMaintenance(asset){let plans=await loadMaint();const id=planId(asset.id),months=Number(document.getElementById('dbmAssetMaintMonths').value||0),nextDate=document.getElementById('dbmAssetMaintNext').value||'';const i=plans.findIndex(p=>p.id===id);if(!months){if(i>=0){plans.splice(i,1);await saveMaint(plans)}return}if(!nextDate){alert('Inserisci la prossima scadenza oppure scegli “Nessuna” nella manutenzione.');throw new Error('maintenance-date-required')}const old=i>=0?plans[i]:null,now=new Date().toISOString();const p={id,propertyId:asset.propertyId,title:`${asset.name} · manutenzione`,months,nextDate,notes:[asset.type,asset.brand,asset.model].filter(Boolean).join(' · '),createdAt:old?.createdAt||now,updatedAt:now};if(i>=0)plans[i]=p;else plans.push(p);await saveMaint(plans)}
async function saveAsset(e){e.preventDefault();const name=document.getElementById('dbmAssetName').value.trim();if(!name)return;await loadAssets();const id=currentAssetId||M.uid(),old=assets.find(x=>x.id===id),file=document.getElementById('dbmAssetPhoto').files?.[0],imageDataUrl=await compressedPhoto(file,old?.imageDataUrl||'');const now=new Date().toISOString(),a={id,propertyId:currentPropertyId,type:document.getElementById('dbmAssetType').value,name,brand:document.getElementById('dbmAssetBrand').value.trim(),model:document.getElementById('dbmAssetModel').value.trim(),serial:document.getElementById('dbmAssetSerial').value.trim(),installedDate:document.getElementById('dbmAssetInstalled').value,warrantyUntil:document.getElementById('dbmAssetWarranty').value,notes:document.getElementById('dbmAssetNotes').value.trim(),imageDataUrl,createdAt:old?.createdAt||now,updatedAt:now};try{await syncMaintenance(a)}catch(err){if(err?.message==='maintenance-date-required')return;throw err}const i=assets.findIndex(x=>x.id===id);if(i>=0)assets[i]=a;else assets.push(a);await saveAssets();document.getElementById('dbmAssetDialog').close();await renderPropertyAssets();document.getElementById('dbmPropertyDialog')?.dispatchEvent(new Event('toggle'))}
async function deleteAsset(){if(!currentAssetId||!confirm('Eliminare questo impianto dalla proprietà? I lavori resteranno registrati.'))return;await loadAssets();assets=assets.filter(x=>x.id!==currentAssetId);await saveAssets();let plans=await loadMaint();plans=plans.filter(p=>p.id!==planId(currentAssetId));await saveMaint(plans);document.getElementById('dbmAssetDialog').close();await renderPropertyAssets()}
async function fillJobProperties(selected=''){const clientId=document.getElementById('dbmJobClient')?.value||'',sel=document.getElementById('dbmJobProperty');if(!sel)return;const a=clientId&&clientId!=='__new__'?await M.propertiesForClient(clientId):[];sel.innerHTML='<option value="">— Nessuna proprietà —</option>'+a.map(p=>`<option value="${esc(p.id)}">${esc(p.name)}${p.address?' · '+esc(p.address):''}</option>`).join('');if(selected)sel.value=selected}
async function fillJobAssets(selected=''){const propertyId=document.getElementById('dbmJobProperty')?.value||'',sel=document.getElementById('dbmJobAsset');if(!sel)return;await loadAssets();const a=assets.filter(x=>x.propertyId===propertyId).sort((x,y)=>(x.name||'').localeCompare(y.name||''));sel.innerHTML='<option value="">— Nessun impianto —</option>'+a.map(x=>`<option value="${esc(x.id)}">${esc(x.name)}${x.brand?' · '+esc(x.brand):''}</option>`).join('');if(selected)sel.value=selected}
function hookJobs(){const baseOpen=M.openJob.bind(M);M.openJob=async id=>{const r=await baseOpen(id);const j=id?await M.mOne('jobs',id):null;await fillJobProperties(j?.propertyId||'');await fillJobAssets(j?.assetId||'');return r};const form=document.getElementById('dbmJobForm'),dlg=document.getElementById('dbmJobDialog');form.addEventListener('submit',()=>{const id=document.getElementById('dbmJobId').value||'',propertyId=document.getElementById('dbmJobProperty')?.value||'',assetId=document.getElementById('dbmJobAsset')?.value||'';jobSaveMetaPromise=(async()=>({id,before:id?null:new Set((await M.mAll('jobs')).map(j=>j.id)),propertyId,assetId}))()},true);dlg.addEventListener('close',async()=>{const pending=jobSaveMetaPromise;jobSaveMetaPromise=null;if(!pending)return;const meta=await pending;setTimeout(async()=>{let id=meta.id;if(!id){const all=await M.mAll('jobs'),created=all.filter(j=>!meta.before?.has(j.id));if(created.length===1)id=created[0].id;else{const title=norm(document.getElementById('dbmJobName')?.value),date=document.getElementById('dbmJobDate')?.value||'';id=created.find(j=>norm(j.title)===title&&j.date===date)?.id||''}}if(!id)return;const j=await M.mOne('jobs',id);if(!j)return;j.propertyId=meta.propertyId||'';j.assetId=meta.assetId||'';await M.mPut('jobs',j);await renderPropertyAssets()},0)})}
wait();
})();
