(()=>{
'use strict';
let M,currentId='';
const KEY='leadsV1';
const wait=()=>{M=window.DBM;if(!M?.setting||!M?.lPut||!M?.clients||!document.getElementById('officeV2'))return setTimeout(wait,100);init()};
const esc=s=>M.esc(s||'');
const norm=s=>String(s||'').trim().toLowerCase();
const money=v=>M.money(Number(v||0));
const sources=['WhatsApp','Facebook','Instagram','Passaparola','Property manager','Cliente esistente','Altro'];
const types=['Property manager','Landlord / Owner','B&B / Guesthouse','Homeowner','Azienda','Collaborazione','Altro'];
const statuses=[['new','Nuovo'],['contacted','Contattato'],['quote','Preventivo'],['won','Acquisito'],['lost','Perso']];
async function all(){try{const raw=await M.setting(KEY,'[]');const a=typeof raw==='string'?JSON.parse(raw):raw;return Array.isArray(a)?a:[]}catch{return[]}}
async function saveAll(a){await M.lPut('settings',{key:KEY,value:JSON.stringify(a)})}
function init(){if(M.__leadsReady)return;M.__leadsReady=true;styles();officePanel();dialog();M.renderLeads=render;}
function styles(){const s=document.createElement('style');s.textContent=`
.dbm-leads-entry{margin-top:12px}.dbm-leads-entry button{width:100%}.dbm-leads-dialog{width:min(calc(100vw - 18px),680px);max-width:680px}.dbm-lead-stats{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin:10px 0}.dbm-lead-stat{border:1px solid #dce6ee;border-radius:13px;padding:10px;background:#fff}.dbm-lead-stat span{display:block;font-size:9.5px;color:#64748b;text-transform:uppercase}.dbm-lead-stat b{display:block;font-size:17px;margin-top:3px}.dbm-lead-list{display:grid;gap:8px}.dbm-lead-row{border:1px solid #dce6ee;border-radius:14px;padding:11px;background:#fff;text-align:left}.dbm-lead-row-top{display:flex;justify-content:space-between;gap:10px}.dbm-lead-row b{font-size:12px}.dbm-lead-row small{display:block;color:#64748b;font-size:9.5px;margin-top:3px}.dbm-lead-pill{font-size:9px;font-weight:800;border-radius:999px;padding:4px 7px;background:#eef6fb;white-space:nowrap}.dbm-lead-next{margin-top:7px;font-size:9.5px;color:#0b6d9c}.dbm-lead-actions{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:10px}.dbm-lead-empty{color:#64748b;font-size:11px;padding:12px 0}.dbm-lead-delete{margin-top:8px}@media(max-width:430px){.dbm-leads-dialog input,.dbm-leads-dialog select,.dbm-leads-dialog textarea{font-size:17px!important}}
`;document.head.appendChild(s)}
function officePanel(){const office=document.getElementById('officeV2');const add=()=>{if(document.getElementById('dbmLeadsOpen'))return;const box=document.createElement('div');box.className='panel dbm-leads-entry';box.innerHTML='<div class="panel-title-row"><div><h2>Contatti & opportunità</h2><p class="hint">Tieni traccia dei contatti commerciali e dei prossimi follow-up.</p></div></div><button id="dbmLeadsOpen" class="secondary full">Apri opportunità</button>';office.appendChild(box);document.getElementById('dbmLeadsOpen').onclick=openDashboard};add();new MutationObserver(add).observe(office,{childList:true})}
function dialog(){if(document.getElementById('dbmLeadsDialog'))return;document.body.insertAdjacentHTML('beforeend',`
<dialog id="dbmLeadsDialog" class="dbm-leads-dialog"><form method="dialog"><div class="dialog-head"><h2>Contatti & opportunità</h2><button type="button" class="icon" data-close-leads>×</button></div><button type="button" id="dbmLeadNew" class="primary full">+ Nuovo contatto</button><div id="dbmLeadStats" class="dbm-lead-stats"></div><div id="dbmLeadList" class="dbm-lead-list"></div></form></dialog>
<dialog id="dbmLeadEditDialog" class="dbm-leads-dialog"><form id="dbmLeadForm" method="dialog"><div class="dialog-head"><h2 id="dbmLeadTitle">Contatto</h2><button type="button" class="icon" data-close-lead-edit>×</button></div><div class="two-cols"><label>Nome / Azienda<input id="dbmLeadName" required></label><label>Telefono<input id="dbmLeadPhone" type="tel"></label></div><label>Email<input id="dbmLeadEmail" type="email"></label><div class="two-cols"><label>Fonte<select id="dbmLeadSource">${sources.map(x=>`<option>${x}</option>`).join('')}</select></label><label>Tipologia<select id="dbmLeadType">${types.map(x=>`<option>${x}</option>`).join('')}</select></label></div><div class="two-cols"><label>Stato<select id="dbmLeadStatus">${statuses.map(([v,l])=>`<option value="${v}">${l}</option>`).join('')}</select></label><label>Prossimo contatto<input id="dbmLeadNext" type="date"></label></div><label>Valore potenziale €<input id="dbmLeadValue" type="number" min="0" step="0.01" inputmode="decimal"></label><label>Note<textarea id="dbmLeadNotes" rows="4"></textarea></label><button class="primary full" value="save">Salva contatto</button><div id="dbmLeadClientActions" class="dbm-lead-actions"></div><button type="button" id="dbmLeadDelete" class="danger full dbm-lead-delete hidden">Elimina contatto</button></form></dialog>`);
document.querySelector('[data-close-leads]').onclick=()=>document.getElementById('dbmLeadsDialog').close();document.querySelector('[data-close-lead-edit]').onclick=()=>document.getElementById('dbmLeadEditDialog').close();document.getElementById('dbmLeadNew').onclick=()=>edit('');document.getElementById('dbmLeadForm').addEventListener('submit',saveLead);document.getElementById('dbmLeadDelete').onclick=removeLead;}
async function openDashboard(){await render();document.getElementById('dbmLeadsDialog').showModal()}
function statusLabel(v){return statuses.find(x=>x[0]===v)?.[1]||'Nuovo'}
async function render(){const a=await all(),today=M.today(),stats=document.getElementById('dbmLeadStats'),list=document.getElementById('dbmLeadList');if(!stats||!list)return;const active=a.filter(x=>x.status!=='won'&&x.status!=='lost'),follow=active.filter(x=>x.nextDate&&x.nextDate<=today).length,quote=a.filter(x=>x.status==='quote').length,won=a.filter(x=>x.status==='won').length;stats.innerHTML=`<div class="dbm-lead-stat"><span>Aperti</span><b>${active.length}</b></div><div class="dbm-lead-stat"><span>Da ricontattare</span><b>${follow}</b></div><div class="dbm-lead-stat"><span>Preventivi</span><b>${quote}</b></div><div class="dbm-lead-stat"><span>Acquisiti</span><b>${won}</b></div>`;if(!a.length){list.innerHTML='<div class="dbm-lead-empty">Nessun contatto commerciale registrato.</div>';return}a.sort((x,y)=>{const ax=x.status==='won'||x.status==='lost'?1:0,ay=y.status==='won'||y.status==='lost'?1:0;return ax-ay||(x.nextDate||'9999').localeCompare(y.nextDate||'9999')||(y.createdAt||'').localeCompare(x.createdAt||'')});list.innerHTML=a.map(x=>`<button type="button" class="dbm-lead-row" data-lead="${esc(x.id)}"><div class="dbm-lead-row-top"><div><b>${esc(x.name)}</b><small>${esc(x.type||'Altro')} · ${esc(x.source||'Altro')}${x.value?` · ${money(x.value)}`:''}</small></div><span class="dbm-lead-pill">${statusLabel(x.status)}</span></div>${x.nextDate?`<div class="dbm-lead-next">Prossimo contatto: ${esc(x.nextDate)}</div>`:''}</button>`).join('');list.querySelectorAll('[data-lead]').forEach(b=>b.onclick=()=>edit(b.dataset.lead))}
async function edit(id){currentId=id||'';const f=document.getElementById('dbmLeadForm');f.reset();document.getElementById('dbmLeadDelete').classList.toggle('hidden',!id);document.getElementById('dbmLeadClientActions').innerHTML='';let x=null;if(id)x=(await all()).find(v=>v.id===id);document.getElementById('dbmLeadTitle').textContent=id?'Modifica contatto':'Nuovo contatto';document.getElementById('dbmLeadName').value=x?.name||'';document.getElementById('dbmLeadPhone').value=x?.phone||'';document.getElementById('dbmLeadEmail').value=x?.email||'';document.getElementById('dbmLeadSource').value=x?.source||'WhatsApp';document.getElementById('dbmLeadType').value=x?.type||'Property manager';document.getElementById('dbmLeadStatus').value=x?.status||'new';document.getElementById('dbmLeadNext').value=x?.nextDate||'';document.getElementById('dbmLeadValue').value=x?.value||'';document.getElementById('dbmLeadNotes').value=x?.notes||'';if(x)await clientActions(x);document.getElementById('dbmLeadEditDialog').showModal()}
async function clientActions(x){const box=document.getElementById('dbmLeadClientActions'),clients=await M.clients(),linked=x.clientId&&clients.find(c=>c.id===x.clientId),same=clients.find(c=>norm(c.name)===norm(x.name));if(linked||same){const c=linked||same;box.innerHTML=`<button type="button" class="secondary" id="dbmLeadClientLinked">Cliente già presente</button><button type="button" class="secondary" id="dbmLeadMarkWon">Segna acquisito</button>`;document.getElementById('dbmLeadClientLinked').disabled=true;document.getElementById('dbmLeadMarkWon').onclick=()=>markWon(c.id);return}box.innerHTML='<button type="button" class="secondary" id="dbmLeadCreateClient">Crea cliente</button><button type="button" class="secondary" id="dbmLeadMarkWon">Segna acquisito</button>';document.getElementById('dbmLeadCreateClient').onclick=createClient;document.getElementById('dbmLeadMarkWon').onclick=()=>markWon('')}
async function currentData(){return{id:currentId||M.uid(),name:document.getElementById('dbmLeadName').value.trim(),phone:document.getElementById('dbmLeadPhone').value.trim(),email:document.getElementById('dbmLeadEmail').value.trim(),source:document.getElementById('dbmLeadSource').value,type:document.getElementById('dbmLeadType').value,status:document.getElementById('dbmLeadStatus').value,nextDate:document.getElementById('dbmLeadNext').value,value:Number(document.getElementById('dbmLeadValue').value||0),notes:document.getElementById('dbmLeadNotes').value.trim()}}
async function saveLead(e){e.preventDefault();const x=await currentData();if(!x.name)return;const a=await all(),i=a.findIndex(v=>v.id===x.id),old=i>=0?a[i]:null;x.createdAt=old?.createdAt||new Date().toISOString();x.updatedAt=new Date().toISOString();x.clientId=old?.clientId||'';if(i>=0)a[i]=x;else a.push(x);await saveAll(a);currentId=x.id;document.getElementById('dbmLeadEditDialog').close();await render()}
async function createClient(){const x=await currentData();if(!x.name)return;const clients=await M.clients();let c=clients.find(v=>norm(v.name)===norm(x.name));if(!c){c={id:M.uid(),name:x.name,phone:x.phone,email:x.email,location:'',notes:`Origine commerciale: ${x.source}${x.notes?' · '+x.notes:''}`};await M.lPut('clients',c)}await markWon(c.id)}
async function markWon(clientId){const x=await currentData(),a=await all(),i=a.findIndex(v=>v.id===x.id),old=i>=0?a[i]:null;x.status='won';x.nextDate='';x.createdAt=old?.createdAt||new Date().toISOString();x.updatedAt=new Date().toISOString();x.clientId=clientId||old?.clientId||'';if(i>=0)a[i]=x;else a.push(x);await saveAll(a);document.getElementById('dbmLeadStatus').value='won';document.getElementById('dbmLeadNext').value='';await clientActions(x);await render()}
async function removeLead(){if(!currentId||!confirm('Eliminare questo contatto commerciale?'))return;const a=(await all()).filter(x=>x.id!==currentId);await saveAll(a);document.getElementById('dbmLeadEditDialog').close();currentId='';await render()}
wait();
})();
