(()=>{
'use strict';
let M,baseOpenJob,baseRenderOffice;
const STATE_PREFIX='review:';
const wait=()=>{M=window.DBM;const form=document.getElementById('dbmJobForm');if(!M?.mOne||!M?.mPut||!M?.mAll||!M?.clients||!M?.setting||!M?.lPut||!M?.openJob||!form)return setTimeout(wait,100);init(form)};
const digits=v=>String(v||'').replace(/\D/g,'');
function waNumber(v){let d=digits(v);if(d.startsWith('00'))d=d.slice(2);if(d.length===8)d='356'+d;return d}
function stateId(jobId){return STATE_PREFIX+jobId}
function fmtDate(v){if(!v)return'';const d=new Date(v);return Number.isNaN(d.getTime())?'':d.toLocaleDateString('it-IT')}
function validUrl(v){try{const u=new URL(String(v||'').trim());return u.protocol==='https:'||u.protocol==='http:'}catch{return false}}
function styles(){if(document.getElementById('dbmReviewStyles'))return;const s=document.createElement('style');s.id='dbmReviewStyles';s.textContent=`#dbmJobReview{margin-top:12px;padding-top:12px;border-top:1px solid #e3ebf1}.dbm-review-head{display:flex;align-items:center;justify-content:space-between;gap:8px}.dbm-review-head b{font-size:15px}.dbm-review-status{font-size:10px;font-weight:800;padding:5px 8px;border-radius:999px;background:#eef5f9;color:#416074}.dbm-review-status.done{background:#e8f7ee;color:#177245}.dbm-review-copy{margin:7px 0 10px;color:#64748b;font-size:11px;line-height:1.35}.dbm-review-actions{display:grid;gap:8px}.dbm-review-actions button{width:100%}.dbm-review-office-stats{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin:10px 0}.dbm-review-office-stat{border:1px solid #dce6ee;border-radius:12px;padding:10px;background:#f8fbfd}.dbm-review-office-stat span{display:block;color:#64748b;font-size:10px}.dbm-review-office-stat b{display:block;margin-top:3px;font-size:18px}`;document.head.appendChild(s)}
function injectJobBox(form){if(document.getElementById('dbmJobReview'))return;const save=form.querySelector('button.primary.full[value="save"]');if(!save)return;save.insertAdjacentHTML('beforebegin',`<section id="dbmJobReview" hidden><div class="dbm-review-head"><b>Recensione Google</b><span id="dbmReviewStatus" class="dbm-review-status">Disponibile</span></div><p id="dbmReviewCopy" class="dbm-review-copy"></p><div id="dbmReviewActions" class="dbm-review-actions"></div></section>`)}
async function getState(jobId){return await M.mOne('history',stateId(jobId))||{id:stateId(jobId),kind:'review',jobId,requestedAt:'',receivedAt:''}}
async function putState(state){state.updatedAt=new Date().toISOString();await M.mPut('history',state)}
function message(link){return `Hi, thank you again for choosing DB Plumbing Services. If you were happy with the work, I’d really appreciate a short Google review. It helps my local business a lot: ${link}\n\nThank you,\nDennis`}
async function renderJobReview(){const box=document.getElementById('dbmJobReview');if(!box)return;const status=document.getElementById('dbmJobStatus')?.value||'';const jobId=document.getElementById('dbmJobId')?.value||'';if(status!=='completed'){box.hidden=true;return}box.hidden=false;const stEl=document.getElementById('dbmReviewStatus'),copy=document.getElementById('dbmReviewCopy'),actions=document.getElementById('dbmReviewActions');if(!jobId){stEl.textContent='Dopo il salvataggio';stEl.classList.remove('done');copy.textContent='Salva prima il lavoro come Completato. Poi riaprilo per decidere se chiedere la recensione.';actions.innerHTML='';return}const job=await M.mOne('jobs',jobId);if(!job){box.hidden=true;return}const clients=await M.clients();const client=clients.find(c=>c.id===job.clientId);const phone=client?.phone||'';const link=String(await M.setting('googleReviewUrl','')).trim();const state=await getState(jobId);if(state.receivedAt){stEl.textContent='Ricevuta '+fmtDate(state.receivedAt);stEl.classList.add('done');copy.textContent='Recensione registrata. Nessun altro messaggio necessario.';actions.innerHTML='';return}stEl.classList.remove('done');if(state.requestedAt){stEl.textContent='Richiesta '+fmtDate(state.requestedAt);copy.textContent='La richiesta è già stata inviata. Segna come ricevuta solo quando la recensione compare davvero.';actions.innerHTML='<button type="button" id="dbmReviewReceived" class="secondary">✓ Segna recensione ricevuta</button>';document.getElementById('dbmReviewReceived').onclick=async()=>{state.receivedAt=new Date().toISOString();await putState(state);await renderJobReview();await renderOfficeReview()};return}if(!link){stEl.textContent='Da configurare';copy.textContent='Per chiedere una recensione serve prima il link diretto Google. Lo imposti una sola volta in Ufficio.';actions.innerHTML='<button type="button" id="dbmReviewSetup" class="secondary">Configura link in Ufficio</button>';document.getElementById('dbmReviewSetup').onclick=()=>M.show('officeV2');return}if(!digits(phone)){stEl.textContent='Telefono mancante';copy.textContent='Il cliente non ha un numero salvato. Aggiungi il telefono al cliente prima di usare WhatsApp.';actions.innerHTML='';return}stEl.textContent='Disponibile';copy.textContent='Usala solo per lavori conclusi e clienti davvero soddisfatti. Nessun invio automatico.';actions.innerHTML='<button type="button" id="dbmAskReview" class="primary">WhatsApp · Chiedi recensione</button>';document.getElementById('dbmAskReview').onclick=async()=>{const state=await getState(jobId);state.requestedAt=new Date().toISOString();await putState(state);await renderJobReview();await renderOfficeReview();window.location.href=`https://wa.me/${waNumber(phone)}?text=${encodeURIComponent(message(link))}`}}
function injectOfficePanel(){const office=document.getElementById('officeV2');if(!office||document.getElementById('dbmReviewOffice'))return;const panel=document.createElement('div');panel.id='dbmReviewOffice';panel.className='panel';panel.innerHTML=`<div class="panel-title-row"><h2>Review Engine</h2><span class="micro">selettivo, non automatico</span></div><p class="hint">Dopo un lavoro completato puoi chiedere una recensione Google via WhatsApp e registrare quando viene ricevuta.</p><div id="dbmReviewOfficeStats" class="dbm-review-office-stats"></div><label>Link diretto recensione Google<input id="dbmGoogleReviewUrl" type="url" inputmode="url" placeholder="https://g.page/r/.../review"></label><button id="dbmSaveReviewUrl" type="button" class="primary full">Salva link recensione</button>`;const backup=[...office.querySelectorAll('.panel')].find(x=>x.textContent.includes('Backup completo PRO'));backup?backup.before(panel):office.appendChild(panel);document.getElementById('dbmSaveReviewUrl').onclick=saveReviewUrl}
async function renderOfficeReview(){const office=document.getElementById('officeV2');if(!office)return;injectOfficePanel();const input=document.getElementById('dbmGoogleReviewUrl');if(input)input.value=await M.setting('googleReviewUrl','');const history=await M.mAll('history');const states=history.filter(x=>x?.kind==='review');const requested=states.filter(x=>x.requestedAt).length,received=states.filter(x=>x.receivedAt).length;const stats=document.getElementById('dbmReviewOfficeStats');if(stats)stats.innerHTML=`<div class="dbm-review-office-stat"><span>Richieste</span><b>${requested}</b></div><div class="dbm-review-office-stat"><span>Ricevute</span><b>${received}</b></div>`}
async function saveReviewUrl(){const input=document.getElementById('dbmGoogleReviewUrl');const value=String(input?.value||'').trim();if(value&&!validUrl(value)){alert('Inserisci un link Google valido che inizi con https://');return}await M.lPut('settings',{key:'googleReviewUrl',value});alert(value?'Link recensione salvato.':'Link recensione rimosso.');await renderOfficeReview()}
function wrap(){baseOpenJob=M.openJob.bind(M);M.openJob=async(...args)=>{const r=await baseOpenJob(...args);await renderJobReview();return r};document.getElementById('dbmJobStatus')?.addEventListener('change',renderJobReview);if(M.renderOffice){baseRenderOffice=M.renderOffice.bind(M);M.renderOffice=async(...args)=>{const r=await baseRenderOffice(...args);await renderOfficeReview();return r}}document.addEventListener('visibilitychange',()=>{if(!document.hidden&&document.getElementById('dbmJobDialog')?.open)renderJobReview()})}
function init(form){if(M.__reviewEngineReady)return;M.__reviewEngineReady=true;styles();injectJobBox(form);wrap();renderOfficeReview()}
wait();
})();
