(()=>{
'use strict';
const M=window.DBM; if(!M)return; let filter='all';
const $=M.$,n=M.n,esc=M.esc,money=M.money;
function total(lines=[]){return lines.reduce((s,l)=>s+n(l.qty)*n(l.sell),0)}function cost(lines=[]){return lines.reduce((s,l)=>s+n(l.qty)*n(l.cost),0)}
function statusLabel(s){return s==='quote'?'Preventivo':s==='active'?'In corso':'Completato'}
function inject(){
 $('jobsV2').innerHTML=`<div class="panel-title-row dbm-top"><div><h1>Lavori & Preventivi</h1><p class="dbm-sub">Dal preventivo al margine reale.</p></div><button id="dbmAddJob" class="primary small">+ Nuovo</button></div><div id="dbmJobFilters" class="segmented"><button data-f="all" class="seg active">Tutti</button><button data-f="quote" class="seg">Preventivi</button><button data-f="active" class="seg">In corso</button><button data-f="completed" class="seg">Completati</button></div><div id="dbmJobList" class="list"></div>`;
 document.body.insertAdjacentHTML('beforeend',`<dialog id="dbmJobDialog"><form id="dbmJobForm" method="dialog"><div class="dialog-head"><h2 id="dbmJobTitle">Nuovo lavoro</h2><button type="button" class="icon" data-close-job>×</button></div><input id="dbmJobId" type="hidden"><div class="two-cols"><label>Data<input id="dbmJobDate" type="date" required></label><label>Stato<select id="dbmJobStatus"><option value="quote">Preventivo</option><option value="active">In corso</option><option value="completed">Completato</option></select></label></div><label>Cliente<select id="dbmJobClient"></select></label><label>Titolo lavoro<input id="dbmJobName" required placeholder="Es. Manutenzione appartamento"></label><label>Località<input id="dbmJobLocation" placeholder="Es. Sliema"></label><label>Pagamento<select id="dbmJobPaid"><option value="unpaid">Da incassare</option><option value="paid">Pagato</option></select></label><div class="dbm-builder-head"><div><b>Interventi e materiali</b><span>Il totale si aggiorna automaticamente.</span></div></div><div id="dbmSuggestions" class="dbm-suggestions"></div><div id="dbmJobLines" class="dbm-line-builder"></div><div class="dbm-line-buttons"><button type="button" id="dbmLabor" class="secondary small">+ Manodopera</button><button type="button" id="dbmMatLine" class="secondary small">+ Materiale</button><button type="button" id="dbmOther" class="secondary small">+ Altro</button></div><div class="dbm-calc"><div><span>Totale cliente</span><b id="dbmJobTotal">€0.00</b></div><div><span>Costo materiali</span><b id="dbmJobCost">€0.00</b></div><div><span>Margine stimato</span><b id="dbmJobMargin">€0.00</b></div></div><label>Note<textarea id="dbmJobNotes" rows="3"></textarea></label><p class="hint">Quando il lavoro diventa “Completato”, viene creato o aggiornato automaticamente il movimento contabile.</p><button class="primary full" value="save">Salva lavoro</button><button type="button" id="dbmDeleteJob" class="danger full hidden">Elimina lavoro</button></form></dialog>`);
 $('dbmAddJob').onclick=()=>M.openJob();$('dbmJobDialog').querySelector('[data-close-job]').onclick=()=>$('dbmJobDialog').close();$('dbmLabor').onclick=()=>addLine('labor');$('dbmMatLine').onclick=()=>addLine('material');$('dbmOther').onclick=()=>addLine('other');$('dbmJobForm').addEventListener('submit',save);$('dbmDeleteJob').onclick=remove;$('dbmJobLines').addEventListener('input',calc);$('dbmJobLines').addEventListener('click',e=>{const b=e.target.closest('.dbm-remove');if(b){b.closest('.dbm-line').remove();calc()}});$('dbmJobFilters').querySelectorAll('[data-f]').forEach(b=>b.onclick=()=>{filter=b.dataset.f;$('dbmJobFilters').querySelectorAll('.seg').forEach(x=>x.classList.toggle('active',x===b));M.renderJobs()});
}
M.renderJobs=async()=>{let a=await M.mAll('jobs');a.sort((x,y)=>(y.date||'').localeCompare(x.date||''));if(filter!=='all')a=a.filter(j=>j.status===filter);const clients=Object.fromEntries((await M.clients()).map(c=>[c.id,c]));const el=$('dbmJobList');if(!el)return;if(!a.length){el.innerHTML='<div class="empty"><strong>Nessun lavoro qui</strong><span>Crea il primo preventivo o lavoro con +.</span></div>';return}el.innerHTML=a.map(j=>{const t=total(j.lines),c=cost(j.lines),cl=clients[j.clientId];return `<button class="row dbm-job" data-job="${j.id}"><div class="dbm-row-main"><div class="row-title">${esc(j.title)}</div><div class="row-sub">${esc(cl?.name||'Nessun cliente')}${j.location?' · '+esc(j.location):''}</div><div class="dbm-tags"><span class="dbm-status ${j.status}">${statusLabel(j.status)}</span>${j.status==='completed'&&j.paid==='unpaid'?'<span class="unpaid-pill">Da incassare</span>':''}</div></div><div class="dbm-numbers"><small>Totale</small><b>${money(t)}</b><small>Margine</small><b class="good">${money(t-c)}</b></div></button>`}).join('');el.querySelectorAll('[data-job]').forEach(b=>b.onclick=()=>M.openJob(b.dataset.job))};
async function addLine(type='labor',d={}){const div=document.createElement('div');div.className='dbm-line';div.dataset.type=type;const mats=(await M.mAll('materials')).sort((a,b)=>a.name.localeCompare(b.name));const opts='<option value="">— scegli dalla banca dati —</option>'+mats.map(m=>`<option value="${m.id}" ${d.materialId===m.id?'selected':''}>${esc(m.name)} · ${money(m.lastPrice)}</option>`).join('');div.innerHTML=`<div class="dbm-line-top"><span class="dbm-type">${type==='labor'?'Manodopera':type==='material'?'Materiale':'Altro'}</span><input class="dbm-desc" value="${esc(d.description||'')}" placeholder="Descrizione"><button type="button" class="dbm-remove">×</button></div>${type==='material'?`<select class="dbm-mat-select">${opts}</select>`:''}<div class="dbm-line-grid"><label>Q.tà<input class="dbm-qty" type="number" min="0" step="0.01" value="${d.qty??1}"></label><label>Prezzo cliente €<input class="dbm-sell" type="number" min="0" step="0.01" value="${d.sell??''}"></label><label>Costo tuo €<input class="dbm-cost" type="number" min="0" step="0.01" value="${d.cost??(type==='labor'?0:'')}"></label></div>`;$('dbmJobLines').appendChild(div);const s=div.querySelector('.dbm-mat-select');if(s)s.onchange=()=>fillMaterial(div,s.value);calc()}
async function fillMaterial(div,id){const m=await M.mOne('materials',id);if(!m)return;div.querySelector('.dbm-desc').value=m.name;div.querySelector('.dbm-cost').value=n(m.lastPrice).toFixed(2);const markup=n(await M.setting('materialMarkup','20'));div.querySelector('.dbm-sell').value=(n(m.lastPrice)*(1+markup/100)).toFixed(2);calc()}
function readLine(d){return{type:d.dataset.type,materialId:d.querySelector('.dbm-mat-select')?.value||'',description:d.querySelector('.dbm-desc').value.trim(),qty:n(d.querySelector('.dbm-qty').value||1),sell:n(d.querySelector('.dbm-sell').value),cost:n(d.querySelector('.dbm-cost').value)}}
function calc(){const lines=[...$('dbmJobLines').querySelectorAll('.dbm-line')].map(readLine),t=total(lines),c=cost(lines);$('dbmJobTotal').textContent=money(t);$('dbmJobCost').textContent=money(c);$('dbmJobMargin').textContent=money(t-c)}
async function suggestions(){const jobs=await M.mAll('jobs'),entries=await M.entries(),freq=new Map();jobs.forEach(j=>(j.lines||[]).filter(l=>l.type!=='material').forEach(l=>{if(!l.description)return;const x=freq.get(l.description)||{count:0,total:0};x.count++;x.total+=n(l.sell);freq.set(l.description,x)}));entries.filter(e=>e.type==='income').forEach(e=>String(e.description||'').split(',').map(x=>x.trim()).filter(x=>x.length>3).forEach(k=>{const x=freq.get(k)||{count:0,total:0};x.count++;freq.set(k,x)}));const top=[...freq.entries()].sort((a,b)=>b[1].count-a[1].count).slice(0,6);$('dbmSuggestions').innerHTML=top.map(([k,v])=>`<button type="button" data-s="${esc(k)}" data-p="${v.total&&v.count?v.total/v.count:0}">${esc(k)}</button>`).join('');$('dbmSuggestions').querySelectorAll('[data-s]').forEach(b=>b.onclick=()=>addLine('labor',{description:b.dataset.s,qty:1,sell:n(b.dataset.p)||''}))}
M.openJob=async id=>{const f=$('dbmJobForm');f.reset();$('dbmJobId').value='';$('dbmJobDate').value=M.today();$('dbmJobStatus').value='quote';$('dbmJobPaid').value='unpaid';$('dbmJobLines').innerHTML='';$('dbmDeleteJob').classList.add('hidden');await M.fillClientOptions($('dbmJobClient'));if(id){const j=await M.mOne('jobs',id);if(!j)return;$('dbmJobTitle').textContent='Modifica lavoro';$('dbmJobId').value=j.id;$('dbmJobDate').value=j.date||M.today();$('dbmJobStatus').value=j.status||'quote';$('dbmJobClient').value=j.clientId||'';$('dbmJobName').value=j.title||'';$('dbmJobLocation').value=j.location||'';$('dbmJobPaid').value=j.paid||'unpaid';$('dbmJobNotes').value=j.notes||'';for(const l of(j.lines||[]))await addLine(l.type,l);$('dbmDeleteJob').classList.remove('hidden')}else{$('dbmJobTitle').textContent='Nuovo lavoro';await addLine('labor')}await suggestions();calc();$('dbmJobDialog').showModal()};
async function save(e){e.preventDefault();const id=$('dbmJobId').value||M.uid(),old=await M.mOne('jobs',id),lines=[...$('dbmJobLines').querySelectorAll('.dbm-line')].map(readLine).filter(l=>l.description||l.sell||l.cost);if(!lines.length){alert('Aggiungi almeno una voce.');return}const j={id,date:$('dbmJobDate').value,clientId:$('dbmJobClient').value,title:$('dbmJobName').value.trim(),location:$('dbmJobLocation').value.trim(),status:$('dbmJobStatus').value,paid:$('dbmJobPaid').value,notes:$('dbmJobNotes').value.trim(),lines,entryId:old?.entryId||''};await M.mPut('jobs',j);if(j.status==='completed')await syncEntry(j);else if(j.entryId){const en=await M.lOne('entries',j.entryId);if(en?.source==='dbm-job')await M.maybeDeleteLedger?.(j.entryId);j.entryId='';await M.mPut('jobs',j)}$('dbmJobDialog').close();await M.refreshHome();await M.renderJobs()}
async function syncEntry(j){const id=j.entryId||M.uid(),t=total(j.lines),vatStatus=await M.setting('vatStatus','article11'),rate=n(await M.setting('vatRate','18')),vat=vatStatus==='article10'?t-t/(1+rate/100):0;await M.lPut('entries',{id,type:'income',date:j.date,clientId:j.clientId,description:j.title,location:j.location,amount:t,vat:Number(vat.toFixed(2)),paid:j.paid,method:'Other',document:'',notes:j.notes,source:'dbm-job',sourceId:j.id,breakdown:j.lines});j.entryId=id;await M.mPut('jobs',j)}
async function remove(){const id=$('dbmJobId').value;if(!id||!confirm('Eliminare questo lavoro/preventivo?'))return;const j=await M.mOne('jobs',id);if(j?.entryId){const e=await M.lOne('entries',j.entryId);if(e?.source==='dbm-job'){const s=M.ledger.transaction('entries','readwrite').objectStore('entries');s.delete(j.entryId)}}await M.mDel('jobs',id);$('dbmJobDialog').close();await M.refreshHome();await M.renderJobs()}
M.maybeDeleteLedger=id=>new Promise((res,rej)=>{const r=M.ledger.transaction('entries','readwrite').objectStore('entries').delete(id);r.onsuccess=()=>res();r.onerror=()=>rej(r.error)});
inject();M.renderJobs();
})();