(()=>{
'use strict';
const M=window.DBM;if(!M)return;const $=M.$,esc=M.esc;
const TASKS=[
{id:'vat-status',title:'VAT: posizione e dichiarazioni',note:'Verifica obblighi pendenti e stato VAT prima di eventuali variazioni.',url:'https://mtca.gov.mt/'},
{id:'vat-change',title:'Passaggio Article 10 / Article 11',note:'MTCA consente la richiesta di cambio tipo registrazione tramite VAT eServices, soggetta a condizioni.',url:'https://mtca.gov.mt/home/2026/05/29/vat-rectification-via-online-portal'},
{id:'income-tax',title:'Income Tax / Self Assessment',note:'Controlla dichiarazioni, scadenze e posizione fiscale.',url:'https://mtca.gov.mt/'},
{id:'class2',title:'Social Security Class 2',note:'Controlla contributi dovuti, eventuale esenzione e scadenze.',url:'https://socialsecurity.gov.mt/en/information-and-applications-for-benefits-and-services/social-security-contributions/'},
{id:'jobsplus',title:'Jobsplus self-employment',note:'Verifica record, data di inizio e designazione dell’attività.',url:'https://jobsplus.gov.mt/self-employed/self-employed-without-employees'}];
function inject(){
 $('officeV2').innerHTML=`<div class="dbm-top"><h1>Ufficio DB</h1><p class="dbm-sub">Burocrazia, incentivi, backup e strumenti di lavoro.</p></div><div class="panel dbm-news"><div class="panel-title-row"><h2>Novità per me</h2><span class="dbm-live">Monitoraggio attivo</span></div><p class="hint">Controllo delle fonti ufficiali Malta per cambi che possono riguardare attività autonoma, VAT, Social Security, Jobsplus, incentivi e settore plumbing/HVAC. Se c’è una novità utile ricevi una notifica.</p><div class="dbm-source-line"><b>Fonti:</b> MTCA · Social Security · Jobsplus · Servizz.gov · Malta Enterprise</div></div><div class="panel"><div class="panel-title-row"><h2>Checklist amministrativa</h2><span class="micro">stato + scadenza</span></div><div id="dbmCompliance"></div></div><div class="panel"><h2>Opportunità & incentivi</h2><div class="dbm-source-cards"><a href="https://www.servizz.gov.mt/en/services/web-06387" target="_blank" rel="noopener"><b>Smart & Sustainable Investment Grant</b><span>Investimenti sostenibili/digitali · fonte ufficiale</span></a><a href="https://www.servizz.gov.mt/en/services/web-02224" target="_blank" rel="noopener"><b>Energy Audit SME Scheme</b><span>Audit energetici per PMI · fonte ufficiale</span></a><a href="https://www.servizz.gov.mt/en/services/web-06372" target="_blank" rel="noopener"><b>Business Development</b><span>Crescita e trasformazione d’impresa · fonte ufficiale</span></a></div></div><div class="panel"><h2>Strumenti rapidi</h2><div class="dbm-office-actions"><button id="dbmOpenEntries" class="secondary">Movimenti contabili</button><button id="dbmOpenReports" class="secondary">Report attuali</button><button id="dbmOpenSetup" class="secondary">Impostazioni VAT</button></div><label>Ricarico materiali predefinito %<input id="dbmMarkup" type="number" min="0" step="1"></label><button id="dbmSaveMarkup" class="primary full">Salva ricarico</button></div><div class="panel"><h2>Backup completo PRO</h2><p class="hint">Include contabilità, clienti, allegati, lavori, materiali, storico prezzi e checklist.</p><button id="dbmBackup" class="primary full">Scarica backup completo</button><label>Ripristina backup PRO<input id="dbmRestore" type="file" accept="application/json,.json"></label></div>`;
 $('dbmOpenEntries').onclick=()=>window.showView?window.showView('entries'):M.show('dashboard');$('dbmOpenReports').onclick=()=>window.showView?window.showView('reports'):M.show('dashboard');$('dbmOpenSetup').onclick=()=>window.showView?window.showView('settings'):M.show('dashboard');$('dbmSaveMarkup').onclick=async()=>{await M.lPut('settings',{key:'materialMarkup',value:$('dbmMarkup').value||'20'});alert('Ricarico materiali salvato')};$('dbmBackup').onclick=backup;$('dbmRestore').onchange=restore;$('dbmCompliance').addEventListener('change',saveTask);
}
M.ensureCompliance=async()=>{for(const t of TASKS)if(!(await M.mOne('compliance',t.id)))await M.mPut('compliance',{...t,status:'todo',due:''})};
M.renderOffice=async()=>{await M.ensureCompliance();await renderTasks();$('dbmMarkup').value=await M.setting('materialMarkup','20')};
async function renderTasks(){const a=await M.mAll('compliance'),el=$('dbmCompliance');if(!el)return;el.innerHTML=a.map(t=>`<div class="dbm-task" data-task="${t.id}"><div class="dbm-task-top"><b>${esc(t.title)}</b><select class="task-status"><option value="todo" ${t.status==='todo'?'selected':''}>Da fare</option><option value="waiting" ${t.status==='waiting'?'selected':''}>In attesa</option><option value="done" ${t.status==='done'?'selected':''}>Fatto</option></select></div><p>${esc(t.note)}</p><div class="dbm-task-foot"><a href="${esc(t.url)}" target="_blank" rel="noopener">Fonte ufficiale ↗</a><input class="task-due" type="date" value="${esc(t.due||'')}"></div></div>`).join('')}
async function saveTask(e){const box=e.target.closest('[data-task]');if(!box)return;const t=await M.mOne('compliance',box.dataset.task);if(!t)return;t.status=box.querySelector('.task-status').value;t.due=box.querySelector('.task-due').value;await M.mPut('compliance',t)}
function dl(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},500)}
function b64(buf){let s='';for(const x of new Uint8Array(buf))s+=String.fromCharCode(x);return btoa(s)}
function from64(s,type){const bin=atob(s),a=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)a[i]=bin.charCodeAt(i);return new Blob([a],{type})}
async function backup(){const data={version:2,kind:'DB Plumbing Manager PRO',exportedAt:new Date().toISOString(),ledger:{entries:await M.entries(),clients:await M.clients(),settings:await ledgerAll('settings'),files:[]},manager:{jobs:await M.mAll('jobs'),materials:await M.mAll('materials'),history:await M.mAll('history'),compliance:await M.mAll('compliance')}};for(const f of await ledgerAll('files'))data.ledger.files.push({id:f.id,name:f.name,type:f.type,data:b64(await f.blob.arrayBuffer())});dl(new Blob([JSON.stringify(data)],{type:'application/json'}),`DB_Plumbing_PRO_backup_${M.today()}.json`)}
function ledgerAll(s){return new Promise((res,rej)=>{const r=M.ledger.transaction(s).objectStore(s).getAll();r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
function clear(db,s){return new Promise((res,rej)=>{const r=db.transaction(s,'readwrite').objectStore(s).clear();r.onsuccess=()=>res();r.onerror=()=>rej(r.error)})}
async function restore(e){const f=e.target.files[0];if(!f)return;if(!confirm('Ripristinare il backup PRO? I dati attuali verranno sostituiti.')){e.target.value='';return}try{const d=JSON.parse(await f.text());if(!d.manager||!d.ledger)throw new Error('format');for(const s of ['entries','clients','settings','files'])await clear(M.ledger,s);for(const s of ['jobs','materials','history','compliance'])await clear(M.db,s);for(const x of d.ledger.entries||[])await M.lPut('entries',x);for(const x of d.ledger.clients||[])await M.lPut('clients',x);for(const x of d.ledger.settings||[])await M.lPut('settings',x);for(const x of d.ledger.files||[])await M.lPut('files',{id:x.id,name:x.name,type:x.type,blob:from64(x.data,x.type)});for(const x of d.manager.jobs||[])await M.mPut('jobs',x);for(const x of d.manager.materials||[])await M.mPut('materials',x);for(const x of d.manager.history||[])await M.mPut('history',x);for(const x of d.manager.compliance||[])await M.mPut('compliance',x);await M.ensureCompliance();await M.refreshHome();await M.renderOffice();alert('Backup PRO ripristinato')}catch(err){console.error(err);alert('Backup PRO non valido')}e.target.value=''}
inject();M.ensureCompliance().then(()=>M.renderOffice());
})();